import { Bot, Sparkles, TriangleAlert } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import type { TicketAiMetadata } from "@/types/ticket";

export function AiClassificationCard({
  ai,
  category,
  priority,
}: {
  ai: TicketAiMetadata | undefined | null;
  category: string | null;
  priority: string | null;
}) {
  const source = ai?.source ?? null;
  const confidence =
    typeof ai?.confidence === "number" ? Math.round(ai.confidence * 100) : null;
  const tone =
    source === "AI"
      ? "border-primary/30 bg-primary/5"
      : source === "FALLBACK"
        ? "border-amber-500/30 bg-amber-500/5"
        : "border-dashed bg-muted/20";

  return (
    <Card className={tone}>
      <CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-start gap-3">
          <div
            className={`flex h-9 w-9 items-center justify-center rounded-lg ${
              source === "AI"
                ? "bg-primary/10 text-primary"
                : source === "FALLBACK"
                  ? "bg-amber-500/15 text-amber-700"
                  : "bg-muted text-muted-foreground"
            }`}
          >
            {source === "FALLBACK" ? (
              <TriangleAlert className="h-4 w-4" />
            ) : source === "AI" ? (
              <Sparkles className="h-4 w-4" />
            ) : (
              <Bot className="h-4 w-4" />
            )}
          </div>
          <div className="space-y-1">
            <div className="flex items-center gap-2 text-sm font-medium">
              {source === "AI"
                ? "AI classification"
                : source === "FALLBACK"
                  ? "Fallback classification"
                  : "Awaiting classification"}
              {confidence !== null ? (
                <Badge variant="muted" className="font-mono text-[11px]">
                  {confidence}% confidence
                </Badge>
              ) : null}
            </div>
            <p className="text-xs text-muted-foreground">
              {source === "FALLBACK"
                ? "AI was unavailable — an admin will review manually."
                : source === "AI"
                  ? "Generated by GPT — admins can override at any time."
                  : "Our classifier will tag this ticket within a few seconds."}
            </p>
          </div>
        </div>
        <div className="flex gap-2 sm:flex-col sm:items-end sm:gap-1 sm:text-right">
          <div>
            <p className="text-[10px] uppercase tracking-wider text-muted-foreground">
              Category
            </p>
            <p className="text-sm font-medium">{category ?? "Pending"}</p>
          </div>
          <div>
            <p className="text-[10px] uppercase tracking-wider text-muted-foreground">
              Priority
            </p>
            <p className="text-sm font-medium">{priority ?? "Pending"}</p>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
